In [1]:
import tensorflow as tf

In [3]:
print(tf.add(1,2))
print(tf.add([1,2], [3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [4]:
x = tf.matmul([[1]], [[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [5]:
import numpy as np
ndarray = np.ones([3,3])

print('Convert Numpy Array to Tensor')
tensor = tf.multiply(ndarray, 42)
print(tensor)

print('Convert Tensor to Numpy Array')
print(np.add(tensor, 1))

print(tensor.numpy())

Convert Numpy Array to Tensor
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
Convert Tensor to Numpy Array
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [6]:
x = tf.random.uniform([3,3])

print('GPU availability:')
print(tf.test.is_gpu_available())

print('Tensor in GPU #0?')
print(x.device.endswith('GPU:0'))


GPU availability:
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False
Tensor in GPU #0?
False


In [7]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)
        
    result = time.time() - start
    print('10 loops: {:0.2f}ms'.format(1000*result))
    
print('On CPU:')
with tf.device('CPU:0'):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith('CPU:0')
    time_matmul(x)
    
if tf.test.is_gpu_available():
    print('ON GPU:')
    with tf.device('GPU:0'):
        x =tf.random.uniform([1000, 1000])
        assert x.device.endswith('GPU:0')
        time_matmul(x)

On CPU:
10 loops: 263.11ms


In [41]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
    f.write('''Line1
    Line2
    Line3
    ''')
    
ds_file = tf.data.TextLineDataset(filename)

In [42]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [43]:
print('Elements of ds_tensors:')
for x in ds_tensors:
    print(x)
    
print('\nElements in ds_file')
for x in ds_file:
    print(x)

Elements of ds_tensors:
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([36  9], shape=(2,), dtype=int32)

Elements in ds_file
tf.Tensor([b'Line1' b'    Line2'], shape=(2,), dtype=string)
tf.Tensor([b'    Line3' b'    '], shape=(2,), dtype=string)
