In [1]:
import tensorflow as tf

In [2]:
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False


In [3]:
layer = tf.keras.layers.Dense(100)

layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [4]:
layer(tf.zeros([10,5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 4.50877964e-01, -2.74376541e-01, -6.11831963e-01,
         -3.61451089e-01, -3.17172766e-01,  5.46023667e-01,
          2.07200885e-01,  2.25896597e-01,  5.26848257e-01,
          4.60529983e-01],
        [-2.90099174e-01,  5.27598917e-01, -1.23894215e-02,
         -5.12286842e-01, -5.42813540e-03,  2.12301314e-01,
         -6.27514601e-01, -5.06219685e-01, -4.62451160e-01,
          2.51076877e-01],
        [ 3.58500123e-01, -1.43210948e-01, -6.23328388e-01,
         -2.61000633e-01, -2.82080799e-01, -3.74930739e-01,
         -4.43706572e-01,  5.74269474e-01,  1.23732924e-01,
          3.95411313e-01],
        [ 5.65178096e-01, -2.03251839e-04, -5.72872698e-01,
         -3.26553643e-01, -2.10733712e-01, -4.05252635e-01,
         -3.91643465e-01,  5.87356150e-01, -5.59764147e-01,
          3.64916980e-01],
        [-3.78797710e-01,  1.00494027e-01, -3.34681779e-01,
          6.01970017e-01, -4.70101595e-01, 

In [7]:
layer.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 4.50877964e-01, -2.74376541e-01, -6.11831963e-01,
         -3.61451089e-01, -3.17172766e-01,  5.46023667e-01,
          2.07200885e-01,  2.25896597e-01,  5.26848257e-01,
          4.60529983e-01],
        [-2.90099174e-01,  5.27598917e-01, -1.23894215e-02,
         -5.12286842e-01, -5.42813540e-03,  2.12301314e-01,
         -6.27514601e-01, -5.06219685e-01, -4.62451160e-01,
          2.51076877e-01],
        [ 3.58500123e-01, -1.43210948e-01, -6.23328388e-01,
         -2.61000633e-01, -2.82080799e-01, -3.74930739e-01,
         -4.43706572e-01,  5.74269474e-01,  1.23732924e-01,
          3.95411313e-01],
        [ 5.65178096e-01, -2.03251839e-04, -5.72872698e-01,
         -3.26553643e-01, -2.10733712e-01, -4.05252635e-01,
         -3.91643465e-01,  5.87356150e-01, -5.59764147e-01,
          3.64916980e-01],
        [-3.78797710e-01,  1.00494027e-01, -3.34681779e-01,
          6.01970017e-01, -4.70101595e-01, 

In [8]:
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 4.50877964e-01, -2.74376541e-01, -6.11831963e-01,
         -3.61451089e-01, -3.17172766e-01,  5.46023667e-01,
          2.07200885e-01,  2.25896597e-01,  5.26848257e-01,
          4.60529983e-01],
        [-2.90099174e-01,  5.27598917e-01, -1.23894215e-02,
         -5.12286842e-01, -5.42813540e-03,  2.12301314e-01,
         -6.27514601e-01, -5.06219685e-01, -4.62451160e-01,
          2.51076877e-01],
        [ 3.58500123e-01, -1.43210948e-01, -6.23328388e-01,
         -2.61000633e-01, -2.82080799e-01, -3.74930739e-01,
         -4.43706572e-01,  5.74269474e-01,  1.23732924e-01,
          3.95411313e-01],
        [ 5.65178096e-01, -2.03251839e-04, -5.72872698e-01,
         -3.26553643e-01, -2.10733712e-01, -4.05252635e-01,
         -3.91643465e-01,  5.87356150e-01, -5.59764147e-01,
          3.64916980e-01],
        [-3.78797710e-01,  1.00494027e-01, -3.34681779e-01,
          6.01970017e-01, -4.70101595e-01, 

In [10]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
        
    def build(self, input_shape):
        self.kernel = self.add_variable('kernel',
                                       shape=[int(input_shape[-1]),
                                              self.num_outputs])
    
    def call(self, input):
        return tf.matmul(input, self.kernel)
    
layer = MyDenseLayer(10)
print(layer(tf.zeros([10,5])))
print(layer.trainable_variables)

Instructions for updating:
Please use `layer.add_weight` method instead.
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.51871115, -0.15961558,  0.4267171 ,  0.01761431,  0.05758756,
         0.19955665,  0.04656911,  0.38953024,  0.5166306 ,  0.37605232],
       [-0.24551806,  0.04783213, -0.40333942, -0.18338057,  0.20801377,
        -0.05494499, -0.11011755,  0.04178309, -0.53246737, -0.34355965],
       [ 0.6217976 , -0.18428513,  0.14614546, -0.10653406,  0.1261009 ,
        -0.46786872, -0.38907504, -0.43426085,  0.17645031, -0.38393947],
       [ 0.15363425,  0.0146243 , -0

In [11]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training = training)
        
        x += input_tensor
        return tf.nn.relu(x)
    
block = ResnetIdentityBlock(1, [1,2,3])
print(block(tf.zeros([1,2,3,3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization/gamma:0', 'resnet_identity_block/batch_normalization/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_1/gamma:0', 'resnet_identity_block/batch_normalization_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_2/gamma:0', 'resnet_identity_block/batch_normalization_2/beta:0']


In [13]:
my_seq = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1, (1,1), input_shape=(None, None, 3)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(2, 1, padding='same'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(3, (1,1)),
    tf.keras.layers.BatchNormalization()
])
my_seq(tf.zeros([1,2,3,3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>