In [1]:
import tensorflow as tf

In [2]:
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False


In [3]:
layer = tf.keras.layers.Dense(100)

layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [4]:
layer(tf.zeros([10,5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [5]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.02470964, -0.13230991, -0.34119317,  0.61056536,  0.32989877,
          0.23142034,  0.5339492 ,  0.18261755, -0.58833885,  0.09029871],
        [-0.28522748, -0.5742746 ,  0.5369187 , -0.58107185,  0.50176054,
         -0.40408957,  0.31170785,  0.14546764,  0.20828551, -0.3133682 ],
        [-0.04387796, -0.00251156,  0.34076673,  0.2606036 , -0.02541989,
         -0.13229966, -0.4417451 , -0.38698542,  0.22465473, -0.41300666],
        [-0.16624564, -0.26001856,  0.20268911, -0.07003975,  0.1647355 ,
          0.3226143 , -0.5017512 ,  0.4131232 ,  0.4581371 , -0.23467633],
        [-0.48415017,  0.5061433 ,  0.3919285 , -0.1971761 , -0.41327778,
          0.17954707, -0.26806858,  0.3252303 , -0.5828887 , -0.3212902 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [6]:
layer.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.02470964, -0.13230991, -0.34119317,  0.61056536,  0.32989877,
          0.23142034,  0.5339492 ,  0.18261755, -0.58833885,  0.09029871],
        [-0.28522748, -0.5742746 ,  0.5369187 , -0.58107185,  0.50176054,
         -0.40408957,  0.31170785,  0.14546764,  0.20828551, -0.3133682 ],
        [-0.04387796, -0.00251156,  0.34076673,  0.2606036 , -0.02541989,
         -0.13229966, -0.4417451 , -0.38698542,  0.22465473, -0.41300666],
        [-0.16624564, -0.26001856,  0.20268911, -0.07003975,  0.1647355 ,
          0.3226143 , -0.5017512 ,  0.4131232 ,  0.4581371 , -0.23467633],
        [-0.48415017,  0.5061433 ,  0.3919285 , -0.1971761 , -0.41327778,
          0.17954707, -0.26806858,  0.3252303 , -0.5828887 , -0.3212902 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [7]:
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.02470964, -0.13230991, -0.34119317,  0.61056536,  0.32989877,
          0.23142034,  0.5339492 ,  0.18261755, -0.58833885,  0.09029871],
        [-0.28522748, -0.5742746 ,  0.5369187 , -0.58107185,  0.50176054,
         -0.40408957,  0.31170785,  0.14546764,  0.20828551, -0.3133682 ],
        [-0.04387796, -0.00251156,  0.34076673,  0.2606036 , -0.02541989,
         -0.13229966, -0.4417451 , -0.38698542,  0.22465473, -0.41300666],
        [-0.16624564, -0.26001856,  0.20268911, -0.07003975,  0.1647355 ,
          0.3226143 , -0.5017512 ,  0.4131232 ,  0.4581371 , -0.23467633],
        [-0.48415017,  0.5061433 ,  0.3919285 , -0.1971761 , -0.41327778,
          0.17954707, -0.26806858,  0.3252303 , -0.5828887 , -0.3212902 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [8]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
        
    def build(self, input_shape):
        self.kernel = self.add_variable('kernel',
                                       shape=[int(input_shape[-1]),
                                              self.num_outputs])
    
    def call(self, input):
        return tf.matmul(input, self.kernel)
    
layer = MyDenseLayer(10)
print(layer(tf.zeros([10,5])))
print(layer.trainable_variables)

Instructions for updating:
Please use `layer.add_weight` method instead.
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.1764316 , -0.5124574 , -0.4056266 , -0.0113259 , -0.49274427,
        -0.33203545, -0.12866688,  0.14936388, -0.5901213 , -0.09270489],
       [ 0.45884913, -0.14761716,  0.18765938, -0.3028564 ,  0.4581974 ,
        -0.5605579 ,  0.39224738, -0.39907947,  0.32790726, -0.5814199 ],
       [-0.38612247,  0.5928183 ,  0.1117925 , -0.3359641 , -0.4553932 ,
        -0.5963932 , -0.12302482, -0.10203177,  0.36074477, -0.20500222],
       [-0.06933331,  0.4870419 ,  0

In [9]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training = training)
        
        x += input_tensor
        return tf.nn.relu(x)
    
block = ResnetIdentityBlock(1, [1,2,3])
print(block(tf.zeros([1,2,3,3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization/gamma:0', 'resnet_identity_block/batch_normalization/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_1/gamma:0', 'resnet_identity_block/batch_normalization_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_2/gamma:0', 'resnet_identity_block/batch_normalization_2/beta:0']


In [10]:
my_seq = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1, (1,1), input_shape=(None, None, 3)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(2, 1, padding='same'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(3, (1,1)),
    tf.keras.layers.BatchNormalization()
])
my_seq(tf.zeros([1,2,3,3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [11]:
my_seq.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, None, None, 1)     4         
_________________________________________________________________
batch_normalization_3 (Batch (None, None, None, 1)     4         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, None, None, 2)     4         
_________________________________________________________________
batch_normalization_4 (Batch (None, None, None, 2)     8         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, None, None, 3)     9         
_________________________________________________________________
batch_normalization_5 (Batch (None, None, None, 3)     12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
___________________________________________________________